import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'app_title': 'E-VALIDATION',
          'internet_exception':
              "We're unable to show results.\nPlease check your data\nconnection",
          'general_exception':
              "We're unable to unable to process your request.\nPlease try again",
          'retry': 'Retry',
          'error_while_communicating_with_server':
              'Error while communicating with server',
          'no_internet': 'No Internet',
          'request_time_out': 'Request Time Out',
          'internal_server_error': 'Internal server error',
          'invalid_url': 'Invalid Url',
          'error_while_communication': 'Error while communication',
          'where_fraud_fails': 'Where fraud fails...',
          'powered_by_blockchain': 'Powered by Blockchain',
          'login': 'Login',
          'don’t_have_an_account_yet': 'Don’t have an account yet?',
          'already_have_an_account': 'Already have an account?',
          'signup': 'Signup',
          'welcome': 'Welcome!',
          'first_name_cannot_be_blank': 'First name cannot be blank!',
          'last_name_cannot_be_blank': 'Last name cannot be blank!',
          'your_account_has_been_created': 'Your account has been created',
          'you_can_now': 'You can now',
          'first_name': 'First Name',
          'email_not_valid': 'Email not valid',
          'last_name': 'Last Name',
          'profile': 'Profile',
          'redeem': 'Redeem',
          'kyc': 'KYC',
          'faqs': 'FAQS',
          'settings': 'Settings',
          'complaints': 'Complaints',
          'points': 'Points',
          'delete_account': 'Delete Account',
          'logout': 'Logout',
          'tap_the_bellow_button_to_scan_the_product':
              'Tap the bellow button to scan\nthe product',
          'scan_now': 'Scan now',
          'product_verified': 'Product Verified!',
          'submit': 'Submit',
          'product_id': 'Product ID',
          'attach_file': 'Attach File',
          'message': 'Message',
          'complain': 'Complain',
          'rewards': 'Rewards',
          'products_scanned': 'Products scanned',
          'solved_complaints': 'Solved Complaints',
          'history': 'History',
          'error': 'Error',
          'email': 'Email',
          'password': 'Password',
          'password_hint': 'Enter password',
          'product_details': 'Product Details',
          'product_name': 'Product Name',
          'barcode': 'Barcode',
          'product_sku': 'Product SKU',
          'supplier': 'Supplier',
          'created_at': 'Created At',
          'expiry_date': 'Expiry Date',
          'fake_product': 'Fake Product',
          'product_scanned': 'Product Scanned',
          'yes': 'Yes',
          'no': 'No',
          'are_you_sure_you_want_to_logout': 'Are You Sure You Want To Logout?',
          'are_you_sure_you_want_to_delete':
              "Are You Sure You Want To Delete?\nPlease Enter Your Registered Email Here.",
          'email_hint': 'Enter Your Email Here',
          'email_star': 'Email*',
          'sorry_you_are_not_eligible_right_now':
              'Sorry! You are not eligible\nright now.',
          'forgot_password': 'Forgot Password',
          'forgot_password_with_question': 'Forgot Password?',
          'create_account': 'Create Account',
          'sign_up': 'Sign Up',
          'full_name': 'Full Name',
          'full_name_hint': 'Enter Full Name',
          'username': 'Username',
          'phone_number': 'Phone Number',
          'phone_no': 'Phone No.',
          'gender': 'Gender',
          'date_of_birth': 'Date of Birth',
          'frequently_asked_questions': 'Frequently Asked Questions',
          'know_your_customer': 'Know Your Customer',
          'change_password': 'Change Password',
          'what_are_the_benefits_of_points': 'What are the benefits of points?',
          'redeem_points': 'Redeem Points',
          'redeem_points_description':
              'Know Your Customer guidelines in financial service require that professionals make an effort to verify the identity, suitability, and risks involved with maintaining a business relationship.',
          'what_is_kyc': 'What is KYC?',
          'kyc_description':
              'The primary motive behind a loyalty program is to retain customers by rewarding them for their repeat purchase behavior',
          'lorem_ipsum_is_simply_dummy_text':
              'Lorem Ipsum is simply dummy text?',
          'simply_dummy_text': 'Simply Dummy Text',
          'lorem_ipsum_description':
              'Lorem Ipsum is simply dummy text used as a placeholder in the printing and typesetting industry to demonstrate the visual form of a document or typeface without relying on meaningful content.',
          'generate_lorem_ipsum_which_looks_reasonable':
              'Generate Lorem Ipsum Which Looks Reasonable?',
          'generate_lorem_ipsum': 'Generate Lorem Ipsum',
          'generate_lorem_ipsum_description':
              'Generating Lorem Ipsum that looks reasonable involves creating placeholder text that mimics the structure and flow of natural language, making it suitable for design mockups, layouts, and testing without distracting from the visual presentation.',
          'upload_your_identity_card_front_and_back':
              'Upload Your Identity Card Front And Back!',
          'user_name': 'User Name',
          'user_lat_lng': 'User LatLng',
          'title': 'Title',
          'user_address': 'User Address',
          'detail': 'Detail',
          'title_cannot_be_blank': 'Title cannot be blank',
          'detail_cannot_be_blank': 'Detail cannot be blank',
          'user_address_cannot_be_blank': 'User Address cannot be blank',
          'user_lat_lng_cannot_be_blank': 'User LatLng cannot be blank',
          'user_name_cannot_be_blank': 'User Name cannot be blank',
          'redeem_your_rewards': 'Redeem Your Rewards',
          'transportation': 'Transportation',
          'restaurants': 'Restaurants',
          'entertainment': 'Entertainment',
          'vouchers': 'Vouchers',
          'earn_more': 'Earn More',
          'voucher_#': 'Voucher #',
          'valid_unit': 'Valid Unit',
          'send_otp': 'Send OTP',
          'voice_chat_gpt': 'Voice chat GPT',
          'update_profile': 'Update Profile',
          'update_password': 'Update Password',
          'existing_password': 'Existing Password',
          'new_password': 'New Password',
          'confirm_password': 'Confirm Password',
          'update': 'Update',
          'profile_setup': 'Profile Setup',
          'please_enter_your_credentials_with_the_following_criteria_below':
              'Please enter your credentials with the following criteria below',
          'phone_number_cannot_be_blank': 'Phone number cannot be blank',
          'date_of_birth_cannot_be_blank': 'Date of birth cannot be blank',
          'gender_cannot_be_blank': 'Gender cannot be blank',
          'verify': 'Verify',
          'verification': 'Verification',
          'resend_code': 'Resend code',
          'send_code': 'Send Code',
          'no_worries_enter_your_email_for_reset_password':
              'No worries! Enter your email address, and\nwe’ll send OTP to reset your password.',
          'password_format_invalid': 'Password format invalid',
          'existing_password_format_invalid':
              'Existing password format invalid',
          'new_password_format_invalid': 'New password format invalid',
          'confirm_password_format_invalid': 'Confirm password format invalid',
          'complain_no': 'Complain No',
          'qr_code_no': 'QR code no.',
          'products_with_qr_code_no': 'Products with QR code no.',
          'scanned_on': 'Scanned on.',
          'reset_password': 'Reset Password',
          'delete': 'Delete',
          'cancel': 'Cancel',
          'notifications': 'Notifications',
          'select_image_source': 'Select Image Source',
          'camera': 'Camera',
          'gallery': 'Gallery',
          'ok': 'OK',
          'done': 'Done',
          'leave': 'Leave',
        },
        'ur_PK': {
          'splash_screen': 'سپلیش اسکرین',
        },
      };
}
