import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'app_title': 'E-VALIDATION',
          'internet_exception':
              "We're unable to show results.\nPlease check your data\nconnection",
          'general_exception':
              "We're unable to unable to process your request.\nPlease try again",
          'retry': 'Retry',
          'error_while_communicating_with_server':
              'Error while communicating with server',
          'no_internet': 'No Internet',
          'request_time_out': 'Request Time Out',
          'internal_server_error': 'Internal server error',
          'invalid_url': 'Invalid Url',
          'error_while_communication': 'Error while communication',
          'where_fraud_fails': 'Where fraud fails...',
          'powered_by_blockchain': 'Powered by Blockchain',
          'login': 'Login',
          'don’t_have_an_account_yet': 'Don’t have an account yet? ',
          'signup': 'Signup',
          'welcome': 'Welcome!',
          'your_account_has_been_created': 'Your account has been created',
          'you_can_now': 'You can now ',
          'first_name': 'First Name',
          'last_name': 'Last Name',
          'profile': 'Profile',
          'redeem': 'Redeem',
          'kyc': 'KYC',
          'faqs': 'FAQS',
          'settings': 'Settings',
          'complaints': 'Complaints',
          'points': 'Points',
          'delete_account': 'Delete Account',
          'logout': 'Logout',
          'tap_the_bellow_button_to_scan_the_product':
              'Tap the bellow button to scan the product',
          'scan_now': 'Scan now',
          'product_verified': 'Product Verified!',
          'submit': 'Submit',
          'product_id': 'Product ID',
          'attach_file': 'Attach File',
          'message': 'Message',
          'complain': 'Complain',
          'rewards': 'Rewards',
          'products_scanned': 'Products scanned',
          'solved_complaints': 'Solved Complaints',
          'history': 'History',
          'error': 'Error',
          'email': 'Email',
          'password': 'Password',
          'password_hint': 'Enter password',
          'product_details': 'Product Details',
          'product_name': 'Product Name',
          'barcode': 'Barcode',
          'product_sku': 'Product SKU',
          'supplier': 'Supplier',
          'created_at': 'Created At',
          'expiry_date': 'Expiry Date',
          'fake_product': 'Fake Product',
          'product_scanned': 'Product Scanned',
          'yes': 'Yes',
          'no': 'No',
          'are_you_sure_you_want_to_logout': 'Are You Sure You Want To Logout?',
          'are_you_sure_you_want_to_delete':
              "Are You Sure You Want To Delete?\nPlease Enter Your Registered Email Here.",
          'email_hint': 'Enter Your Email Here',
          'email_star': 'Email*',
          'sorry_you_are_not_eligible_right_now':
              'Sorry! You are not eligible right now.',
          'forgot_your_password': 'Forgot your Password?',
          'create_account': 'Create Account',
          'sign_up': 'Sign Up',
          'full_name': 'Full Name',
          'full_name_hint': 'Enter Full Name',
          'username': 'Username',
          'phone_number': 'Phone Number',
          'gender': 'Gender',
          'birthday': 'Birthday',
          'frequently_asked_questions': 'Frequently Asked Questions',
          'know_your_customer': 'Know Your Customer',
          'change_password': 'Change Password',
          'what_are_the_benefits_of_points': 'What are the benefits of points?',
          'what_is_kyc': 'What is KYC?',
          'lorem_ipsum_is_simply_dummy_text':
              'Lorem Ipsum is simply dummy text?',
          'generate_lorem_ipsum_which_looks_reasonable':
              'Generate Lorem Ipsum Which Looks Reasonable?',
          'upload_your_identity_card_front_and_back':
              'Upload Your Identity Card Front And Back!',
          'user_name': 'User Name',
          'user_lat_lng': 'User LatLng',
          'title': 'Title',
          'user_address': 'User Address',
          'detail': 'Detail',
          'title_cannot_be_blank': 'Title cannot be blank',
          'detail_cannot_be_blank': 'Detail cannot be blank',
          'user_address_cannot_be_blank': 'User Address cannot be blank',
          'user_lat_lng_cannot_be_blank': 'User LatLng cannot be blank',
          'user_name_cannot_be_blank': 'User Name cannot be blank',
        },
        'ur_PK': {
          'splash_screen': 'سپلیش اسکرین',
        },
      };
}
